service: additional-restrictions-grant

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage}
  dbname: additionalRestrictionsGrantDb
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

resources:
  Resources:
    additionalRestrictionsGrantSupportingDocumentsBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.bucket}
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          VersioningConfiguration:
            Status: Enabled
          CorsConfiguration:
            CorsRules:
              -
                AllowedOrigins:
                  - '*'
                AllowedHeaders:
                  - '*'
                AllowedMethods:
                  - PUT
                  - POST
                MaxAge: 3000
    additionalRestrictionsGrantDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow internal VPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 172.31.0.0/16

    additionalRestrictionsGrantDb:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5
        DBInstanceIdentifier: "${self:service}-db-${self:provider.stage}"
        DBInstanceClass: "db.t2.small"
        DBName: ${self:provider.dbname}
        DeletionProtection: false
        Engine: "postgres"
        EngineVersion: "11.7"
        MasterUsername: ${env:MASTER_USERNAME}
        MasterUserPassword: ${env:MASTER_USER_PASSWORD}
        MultiAZ: true
        PubliclyAccessible: false
        StorageEncrypted: true
        VPCSecurityGroups:
        - Fn::GetAtt:
          - additionalRestrictionsGrantDbSecurityGroup
          - GroupId
        Tags:
          -
            Key: "Name"
            Value: "additionalRestrictionsGrantsDb"
      DeletionPolicy: "Snapshot"

custom:
  bucket: ${self:service}-supporting-documents-${self:provider.stage}
  aliases:
    staging: staging-additionalrestrictionsgrant.hackney.gov.uk
    production: additionalrestrictionsgrant.hackney.gov.uk
  certificate-arn:
    staging: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
    production: arn:aws:acm:us-east-1:153306643385:certificate/71728a39-cd3e-4570-a440-e87f84ef9a0d

